// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATo1TH2t861ie1HviHSRgCzFqGP1HpPEs',
    appId: '1:399963045322:web:3dc3d6e99a89e1f73b2333',
    messagingSenderId: '399963045322',
    projectId: 'lifedrop-94bad',
    authDomain: 'lifedrop-94bad.firebaseapp.com',
    storageBucket: 'lifedrop-94bad.firebasestorage.app',
    measurementId: 'G-ERN0PYBTS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7t4HFmKZInPp1zAgLS8IYkHMY3zDlnsA',
    appId: '1:399963045322:android:822201fad32f306c3b2333',
    messagingSenderId: '399963045322',
    projectId: 'lifedrop-94bad',
    storageBucket: 'lifedrop-94bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUhQW13q3hPTQQXmiAYbeiJhHtBj0tvg',
    appId: '1:399963045322:ios:4677d29351fb0e0e3b2333',
    messagingSenderId: '399963045322',
    projectId: 'lifedrop-94bad',
    storageBucket: 'lifedrop-94bad.firebasestorage.app',
    iosBundleId: 'com.example.lifedrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEUhQW13q3hPTQQXmiAYbeiJhHtBj0tvg',
    appId: '1:399963045322:ios:4677d29351fb0e0e3b2333',
    messagingSenderId: '399963045322',
    projectId: 'lifedrop-94bad',
    storageBucket: 'lifedrop-94bad.firebasestorage.app',
    iosBundleId: 'com.example.lifedrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATo1TH2t861ie1HviHSRgCzFqGP1HpPEs',
    appId: '1:399963045322:web:e9899c40371264e43b2333',
    messagingSenderId: '399963045322',
    projectId: 'lifedrop-94bad',
    authDomain: 'lifedrop-94bad.firebaseapp.com',
    storageBucket: 'lifedrop-94bad.firebasestorage.app',
    measurementId: 'G-9CBW2GSGSL',
  );
}
